# Generated by Django 5.2.5 on 2026-03-03 07:54

from django.db import migrations
from django.utils.text import slugify

LOOKING_FOR_TEAMMATES = [
    "Frontend Developer",
    "Backend Developer",
    "Fullstack Developer",
    "ML Engineer",
    "UI/UX Designer",
    "Data Scientist",
    "DevOps Engineer",
    "Mobile Developer",
]

SKILLS_DATA = [
    "React",
    "TypeScript",
    "Python",
    "Node.js",
    "Django",
    "FastAPI",
    "Docker",
    "PostgreSQL",
    "MongoDB",
    "AWS",
]

CATEGORY_DATA = [
    "Hackathon Project",
    "Side Project",
    "Open Source",
    "AI",
    "ML",
    "Web3",
    "Blockchain",
    "Iot",
    "UI/UX",
]


def seed_data(apps, scheme_editor):
    Looking_for = apps.get_model("projects", "Looking_for")
    Skilled_tag = apps.get_model("projects", "Skilled_tag")
    Category_tag = apps.get_model("projects", "Category_tag")
    
    for name in LOOKING_FOR_TEAMMATES:
        Looking_for.objects.get_or_create(name=name, slug=slugify(name))

    for name in SKILLS_DATA:
        Skilled_tag.objects.get_or_create(name=name, slug=slugify(name))

    for name in CATEGORY_DATA:
        Category_tag.objects.get_or_create(name=name, slug=slugify(name))


def unseed_data(apps, scheme_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_data,unseed_data)
    ]
